main: holiday.garet.skyblock.SimpleSkyblock
name: SimpleSkyblock
version: 1.4.0
api-version: 1.13
author: garet90
description: A simple skyblock plugin.
load: STARTUP
commands:
 island:
  description: The skyblock main command.
  usage: /island [args]
  permission: skyblock.island
  permission-message: You don't have the skyblock.island permission.
 is:
  description: Alias of /island
  usage: /is [args]
  permission: skyblock.island
  permission-message: You don't have the skyblock.island permission.
 balance:
  description: See how much money a player has.
  usage: /balance [player]
  permission: skyblock.economy
  permission-message: You don't have the skyblock.economy permission.
 bal:
  description: Alias of /balance
  usage: /bal [player]
  permission: skyblock.economy
  permission-message: You don't have the skyblock.economy permission.
 pay:
  description: Send money to another player.
  usage: /pay <player> <amount>
  permission: skyblock.economy
  permission-message: You don't have the skyblock.economy permission.
 fly:
  description: Toggle flight.
  usage: /fly
  permission: skyblock.fly
  permission-message: You don't have the skyblock.fly permission.
 shout:
  description: Shout to whole server.
  usage: /shout <message>
  permission: skyblock.shout
  permission-message: You don't have the skyblock.shout permission.
 trade:
  description: Trade with another player.
  usage: /trade <player>
  permission: skyblock.trade
  permission-message: You don't have the skyblock.trade permission.
 spawn:
  description: Go to server spawn.
  usage: /spawn
  permission: skyblock.spawn
  permission-message: You don't have the skyblock.spawn permission.